### ISSUE TITLE
您好请问在data_loader中为什么要对image进行resize（56）操作?

### ISSUE THREAD

**Issue by Harrypotterrrr** [Epiphqny/Colorization#1]
img_resiz 变量参见data_loader.py 32行 rgb2lab函数接受参数的维数不能是二维 且.shape[-1] 应该为3

**Comment by Epiphqny** [comment]
> img_resiz 变量参见data_loader.py 32行 rgb2lab函数接受参数的维数不能是二维 且.shape[-1] 应该为3

resize是为了将target变成56的大小，网络的输入仍然是224。这样做的好处是，由于是pixel-wise的分割，相当于每个pixel做分类计算损失函数，总的损失是所有像素的损失之和，因此target像素数较少可以让batchsize设的大一点，方便训练。第二个问题不懂是什么意思，rgb2lab本来就应该是输入彩色图像，不然就没法分离出颜色来作为监督信息

**Comment by Harrypotterrrr** [comment]
谢谢您及时的回复，第二个问题是我自己的问题，我的dataset中夹杂了gif格式的图片，因此PIL.open后的图片大小是(H,W) 二维元组

**Comment by Epiphqny** [comment]
好的，如果对您有用的话请点个赞吧，多谢🙏

Harrypotterrrr <notifications@github.com>于2019年3月27日 周三上午11:23写道：

**Comment by Epiphqny** [comment]
好的，如果对您有用的话请点个star吧，谢谢

Harrypotterrrr <notifications@github.com>于2019年3月27日 周三上午11:23写道：

**Comment by Epiphqny** [comment]
> 谢谢您及时的回复，第二个问题是我自己的问题，我的dataset中夹杂了gif格式的图片，因此PIL.open后的图片大小是(H,W) 二维元组

不客气 如果喜欢的话请点个star再走吧
