### ISSUE TITLE
你好，请问你代码中prior_probs.npy及pts_in_hull.npy是怎样得到的呢？

### ISSUE THREAD

**Issue by Chen-Song** [Epiphqny/Colorization#2]
你好：

请问你代码中prior_probs.npy及pts_in_hull.npy是怎样得到的呢？
若我想在CIFAR10数据集上运行你的代码，这两个文件还需要进行修改吗？其他还有什么注意点呢？谢谢。

**Comment by Epiphqny** [comment]
> 你好：
> 
> 请问你代码中prior_probs.npy及pts_in_hull.npy是怎样得到的呢？
> 若我想在CIFAR10数据集上运行你的代码，这两个文件还需要进行修改吗？其他还有什么注意点呢？谢谢。

时间太久我记不清了，印象中好像是作者提供的，pts_in_hull.npy表示颜色的编码映射，prior_probs.npy表示对imagenet中不同类别的权重，如果是在cifar10上训练的话，可能你需要重新设置权重，或者均分权重。我是基于作者的caffe代码复现的https://github.com/richzhang/colorization，更多的问题你可以去看他的issue以及原始论文。

**Comment by Chen-Song** [comment]
谢谢你的回复。
祝好。

**Comment by Epiphqny** [comment]
> 谢谢你的回复。
> 祝好。

我刚刚想起来，之前的回复说错了一个地方，prior_probs.npy不是对imagenet类别的权重，而是对313个颜色类别的权重，这样你在新的数据集上训练应该是不用更改的，直接用这两个文件就行

**Comment by Chen-Song** [comment]
你好，重着色的训练速度好像挺慢的，我训练STL10数据集（96*96,105000张），batch_size=210，NIN网络架构，一个epoch大约40分钟，请问你训练速度也是这样吗？
还有一个问题：我按照你代码里面的设置，发现loss基本不下降，还是是因为着色任务的loss本来就应该是这种情况？
前30epoch的loss:
158.7432599067688, 158.6387291252613, 158.17271053791046, 158.60172459483147, 158.00926154851913, 158.3239342570305, 158.59686651825905, 158.47332759201527, 158.36015966534615, 157.94744223356247, 158.55983117222786, 158.28294672071934, 158.49212469160557, 158.26879939436913, 158.92559829354286, 158.0550045967102, 158.19766980409622, 158.79940703511238, 158.0030116289854, 158.3397980928421, 158.2301221191883, 158.02151322364807, 157.8200246244669, 158.09718157351017, 157.49421805143356, 157.98869259655476, 159.04879620671272, 157.63684959709644, 157.6059437096119, 157.51368591189384.

谢谢你。

**Comment by Epiphqny** [comment]
> 你好，重着色的训练速度好像挺慢的，我训练STL10数据集（96*96,105000张），batch_size=210，NIN网络架构，一个epoch大约40分钟，请问你训练速度也是这样吗？
> 还有一个问题：我按照你代码里面的设置，发现loss基本不下降，还是是因为着色任务的loss本来就应该是这种情况？
> 前30epoch的loss:
> 158.7432599067688, 158.6387291252613, 158.17271053791046, 158.60172459483147, 158.00926154851913, 158.3239342570305, 158.59686651825905, 158.47332759201527, 158.36015966534615, 157.94744223356247, 158.55983117222786, 158.28294672071934, 158.49212469160557, 158.26879939436913, 158.92559829354286, 158.0550045967102, 158.19766980409622, 158.79940703511238, 158.0030116289854, 158.3397980928421, 158.2301221191883, 158.02151322364807, 157.8200246244669, 158.09718157351017, 157.49421805143356, 157.98869259655476, 159.04879620671272, 157.63684959709644, 157.6059437096119, 157.51368591189384.
> 
> 谢谢你。

我是用的imagenet数据集训练的，如果你用其他数据集的话，可能需要重新调一下参数，比如把lr缩小或者放大10倍看一下有没有影响。
