### ISSUE TITLE
您好，想问一下您，训练完之后，可以做什么呢

### ISSUE THREAD

**Issue by wang-haiyang123** [Epiphqny/Colorization#3]
期待您的回复

**Comment by Epiphqny** [comment]
> 期待您的回复

可以做图像上色任务，这本身也属于图像自监督学习的任务，可以用来提特征聚类，相当于无监督学习。具体可以参考这篇论文 https://arxiv.org/abs/1603.08511

**Comment by wang-haiyang123** [comment]
> > 期待您的回复
> 
> 可以做图像上色任务，这本身也属于图像自监督学习的任务，可以用来提特征聚类，相当于无监督学习。具体可以参考这篇论文 https://arxiv.org/abs/1603.08511

您好，感谢您的回复。因为我是新手，想问一下您，我看您的代码是只有训练部分的，对吗?训练之后的模型，如果我用来做图像上色任务，需要我自己完成后续的代码对吗？

**Comment by Epiphqny** [comment]
> > > 期待您的回复
> > 
> > 
> > 可以做图像上色任务，这本身也属于图像自监督学习的任务，可以用来提特征聚类，相当于无监督学习。具体可以参考这篇论文 https://arxiv.org/abs/1603.08511
> 
> 您好，感谢您的回复。因为我是新手，想问一下您，我看您的代码是只有训练部分的，对吗?训练之后的模型，如果我用来做图像上色任务，需要我自己完成后续的代码对吗？

是的

**Comment by wang-haiyang123** [comment]
> > > > 期待您的回复
> > > 
> > > 
> > > 可以做图像上色任务，这本身也属于图像自监督学习的任务，可以用来提特征聚类，相当于无监督学习。具体可以参考这篇论文 https://arxiv.org/abs/1603.08511
> > 
> > 
> > 您好，感谢您的回复。因为我是新手，想问一下您，我看您的代码是只有训练部分的，对吗?训练之后的模型，如果我用来做图像上色任务，需要我自己完成后续的代码对吗？
> 
> 是的

好的 谢谢
